### ISSUE TITLE
🔬 Research Twitter/X SEO

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/VelaptorDocs#105]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

@CalvinWilkinson needs to add information here about any changes on how Twitter handles changes to SEO since the rebranding to "X"

The metadata/SEO config is in the _**docusaurus.config.js**_

```json
      metadata: [
        {
          name: 'twitter:card',
          content: 'summary_large_image'
        },
        {
          name: 'twitter:image',
          content: 'https://docs.velaptor.io/img/meta-image.jpg'
        },
        {
          name: 'twitter:site',
          content: '@KDCoder'
        },
        {
          name: 'twitter:creator',
          content: '@KDCoder'
        },
        {
          name: 'keywords',
          content: 'Velaptor, 2D, Game, Game Development, Framework, Cross Platform, C#, .NET, OpenGL'
        }
      ],
```

### Info Found

The documentation on the meta-data can be found [here](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary#:~:text=Images%20must%20be%20less%20than,animated%20GIF%20will%20be%20used.)

It has been discovered that the image must be square.  If the image is rectangle, then it will be cropped.  This needs to be fixed.

### Acceptance Criteria

- [x] Research info posted here in this issue
- [x] Issue created to make changes

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
