### ISSUE TITLE
📜Update input guides for v1.0.0-preview.25

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#107]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update the _**Keyboard Input**_ and _**Mouse Input**_ guides for _**Velaptor**_ version _**v1.0.0-preview.25**_.

This version of **_Velaptor_** has API changes that should be reflected in the guides.

> **Warning**
> DO NOT UPDATE OTHER VERSIONS OF THE GUIDES
> These changes are only for the upcoming version stated above.

### Acceptance Criteria

- [x] _**Keyboard Input**_ guide updated
- [x] _**Mouse Input**_ guide updated
- [x] _**Velaptor**_ version _**v1.0.0-preview.25**_ released with API doc release first before this is completed.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
