### ISSUE TITLE
📋Move default doc tool version to repo variable

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#120]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Currently, the [DefaultDocumentation](https://github.com/Doraku/DefaultDocumentation) dotnet tool version is hard coded into the `DefaultDocTool.ts` file.  This needs to be swapped with a GitHub API call to get a repo variable value that contains the version.

The name of the repo variable should be _**DEFAULT_DOC_DOTNET_TOOL_VERSION**_.

Wait until the issue shown below in the dependency section has been completed before this is done.  This means that the GitHub API call can be used by the deno package created from the issue below.

### Acceptance Criteria

- [x] Default doc version pulled from repo variable
- [x] Hard coded version removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Issue Dependencies

- KinsonDigital/kd_clients#2
    - This will be the deno library/package that will provide the GitHub API clients

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
