### ISSUE TITLE
📜Update guides and latest API changes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#126]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update all of the guides for Velaptor version _**v1.0.0-preview.30**_ to use the new content loading changes implemented in that version of Velaptor.  Also, update to the latest upcoming API changes by manually adding the latest API changes that reference the branch for issue KinsonDigital/Velaptor#791

The guides to update are:
1. Rendering Text guide
1. Rendering Textures guide
1. Rendering With An Atlas Texture Guide
1. Sounds guide

Remove the extra step in the **Render Text** guide from all doc versions.  The steps 3.2 and 4.4 are the same.  Remove step 4.4

### Acceptance Criteria

- [x] Rendering Text guide updated
- [x] Rendering Textures guide updated
- [x] Rendering With An Atlas Texture guide updated
- [x] Sounds guide updated
- [x] Duplicate **_Step 4.4 Load Font_** removed from all of the other versions of the guides.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
