### ISSUE TITLE
📋Add CICD status checks to release workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#133]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Add the CICD lint and build status checks to the _**api-release.yml**_ and _**prod-release.yml**_ workflows.

This will entail steps being added to the required jobs for each workflow that runs `deno lint` and `deno run deno-check.ts` commands.

### Acceptance Criteria

- [ ] Deno lint step added to _**api-release.yml**_ workflow
- [ ] Deno check step added to _**api-release.yml**_ workflow
- [ ] Deno lint step added to _**prod-release.yml**_ workflow
- [ ] Deno check step added to _**prod-release.yml**_ workflow

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
It was decided that most of the time the cicd scripts do not change and the PR status checks are enough to make sure they stay stable.  Adding these would be necessary time added to releases.
