### ISSUE TITLE
📋Migrate from yarn to pnpm

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#138]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Migrate the current package management system of _**yarn**_ to _**pnpm**_.

**Additional Info:**
- [pnpm docs](https://pnpm.io/)
- [Migration Guide](https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04)

### **Follow these steps to migrate:**
Sure, here are the steps to migrate from Yarn to PNPM for a Docusaurus website:

1. **Install PNPM**: You can install PNPM globally using npm with the command `npm install -g pnpm`¹.
1. **Delete node_modules**: You can use `npx npkill` to delete the `node_modules` directory¹.
    1. **Add to package.json**: Add the following to your `package.json` file under "scripts": `{ "preinstall": "npx only-allow pnpm" }`. 
    > **Note**
    > This will prevent other developers from accidentally installing dependencies with anything other than PNPM¹.
1. **Run `pnpm import`**: This command will create a `pnpm-lock.yaml` file based on `yarn.lock`¹.
1. **Remove yarn.lock**: Remove the `yarn.lock` file from your project¹.
1. **Install dependencies**: Run `pnpm i` to install the dependencies¹.
1. **Replace `yarn` with `pnpm`**: Replace all instances of `yarn` with `pnpm` in all `package.json` and other files. For example, change `yarn test` to `pnpm test`¹.

Please note that PNPM doesn't use dependency hoisting by default. If you have a package A that imports a package B but doesn’t explicitly specify B in the `dependencies` or `devDependencies`, then the execution will fail.

Here is a code block that shows the changes in `package.json`:
```json
{
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    ...
  },
  ...
}
```

### **Update NPM Scripts:**
Also, update the npm scripts in the _**package.json**_ to use `pnpm` instead of `yarn`.
```diff
  "scripts": {
    "docusaurus": "docusaurus",
-    "start": "yarn install && docusaurus start",
+    "start": "pnpm i && docusaurus start",
-   "build": "yarn install && docusaurus build",
+    "build": "pnpm i && docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids",
    "typecheck": "tsc",
    "clean": "@powershell Remove-Item .\\node_modules -Force -Recurse",
    "preinstall": "npx only-allow pnpm"
  },
```

### **Update API Release Workflow:**
Update the _**api-release.yml**_ workflow to use `pnpm`
1. Install dependencies step
    ```diff
    - - name: Install Dependencies (YARN)
    + - name: Install Dependencies (pnpm)
    -  run: yarn install;
    +  run: pnpm i;
    ```
2. Create docusaurus version step
    ```diff
    - name: Create Docusaurus Version (${{ inputs.api-version }})
      run: |
        $version = "${{ inputs.api-version }}";
        $version = $version.StartsWith("v") ? $version.Substring(1) : $version;
    -   pnpm docusaurus docs:version $version;
    +   yarn docusaurus docs:version $version;
    ```
3. Build site step
    ```diff
     - name: Build Site
    -   run: yarn build
    +   run: pnpm build
    ```

### **Update API Release Workflow:**
Update the _**prod-release.yml**_ workflow to use `pnpm`
1. Install dependencies step
    ```diff
    - - name: Install Dependencies (YARN)
    + - name: Install Dependencies (pnpm)
    -  run: yarn install;
    +  run: pnpm i
    ```
2. Build site step
    ```diff
     - name: Build Site
    -   run: yarn build
    +   run: pnpm build
    ```

### **Update Build Status Check Workflow:**
Update the _**build-status-check.yml**_ workflow to use `pnpm`
1. Setup docusaurus step
    ```diff
     - name: Setup Docusaurus
    -  run: yarn install
    +  run: pnpm install
    ```
2. Build step
    ```diff
     - name: Build
    -  run: yarn build
    +  run: pnpm build
    ```

### **Update VSCode Tasks Config:**
Update the `tasks.json` VSCode config file to use `pnpm`
```diff
{ // BUILD
	"label": "build",
	"dependsOn": [ "Disable Testing Environment" ],
	"type": "shell",
	"windows": {
-		"command": "yarn",
+		"command": "pnpm",
		"args": ["build"]
	}
},
```

### **Update Project README:**
Update the _**README.md**_ file to use `pnpm`
Replace the entire **Common Development Commands** section with the markdown below
```md
### **Install npm packages**

Use the command `pnpm i` or `pnpm install` to install all of the project's dependencies.

### **Local Development Server**

Use the command `pnpm start` to starts a local development server. Most changes are reflected HMR(Hot Module Replacement) without having to restart the server.

### **Build**

Use the command `pnpm build` to produce a production build of the site. This command puts the production build into the `build` directory and can be served using any static content hosting service.

### **Serve Build Locally**

Use the command `pnpm serve` to run a local server of the production version of the website.
```

Update the text of the docusaurus link in the **_REAME.md_** file:
```diff
- This website is built using [Docusaurus 2](https://docusaurus.io/), a modern static website generator.
+ This website is built using [Docusaurus 3](https://docusaurus.io/), a modern static website generator.
```

```[tasklist]
### Acceptance Criteria
- [x] `yarn` removed from the project
- [x] `pnpm` added to the project
- [x] The _**api-release.yml**_ workflow updated to use `pnpm`
- [x] The _**prod-release.yml**_ workflow updated to use `pnpm`
- [x] The _**build-status-check.yml**_ workflow updated to use `pnpm`
- [x] The _**tasks.json**_ file updated to use `pnpm`
- [x] The _**README.md**_ file updated for `pnpm`
- [x] Docusaurus link in _**README.md**_ file udpated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
