### ISSUE TITLE
📜Fix guides for v1.0.0-preview.30

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#140]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

While upgrading the Velaptor tutorial projects to Velaptor version **_v1.0.0-preview.30_**, it was discovered that the guides were not updated regarding the renderer creation code.

**Example:**
In the **_Game.cs_** file, the constructor needs to be upgraded to meet the changes of version _**v1.0.0-preview.30**_, but the guides are not updated.
```cs
public Game()
{
    Title = "Atlas Textures";
    Width = 500;
    Height = 500;

    var rendererFactory = new RendererFactory();
    this.textureRenderer = rendererFactory.CreateTextureRenderer(); 👈🏻 Incorrect

    this.batcher = rendererFactory.CreateBatcher();
}
```

There are other areas that need improvement as well.  Find all of the areas and fix them.

Also, update the project links to link to version _**v1.0.0-preview.30**_

```[tasklist]
### Acceptance Criteria
- [x] Guides for version _**v1.0.0-preview.30**_ updated
- [x] Update and improve the Audio component
- [x] Update all `<TutorialLink/>` component versions
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
