### ISSUE TITLE
📋Move velaptor tutorials into repo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#142]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Move all of the C# tutorial projects from the _**VelaptorTutorials**_ repository into the _**VelaptorDcos**_ repository.

**Purpose:**
The reason for this is to make it easier to manage updates to the tutorials project when updating or adding guides to the doc site.   Each guide links to the _**VelaptorTurorials**_ repo project via a GitHub URL with a tag.  This in itself is difficult to manage because we have to not only work in 2 separate repos but also have to manage tags.

Moving all of these projects into the docs will give us the ability to update the tutorial docs **WITH** the docs and have them released at the same time.

**Things To Do:**
1. Create a separate root folder on the site that will hold the solution and projects
2. Create a build status check workflow for the tutorial projects
3. Add a build step to the _**prod-release.yml**_ workflow
    > **Note**
    > Use the reusable workflow from the infrastructure repo
4. Create a deno script that can update the Velaptor NuGet package in the C# projects and be executed in the _**api-release.yml**_ workflow
    > **Note**
    > Add this step between the `Update Website version` and `Build Site` steps
5. Add a build step to the _**api-release.yml**_ workflow
    > **Note**
    > Add this step after the NuGet packages have been updated.  This will  _**NOT**_ use the reusable workflow.  Just do a standard dotnet build of the entire solution.
6. Update the `<TutorialLink/>` component to use the _**VelaptorDocs**_ repository in the URL instead of the _**VelaptorTutorials**_ repository.
7. Create deno script to update `<TutorialLink/>` components with the new version of an API release ran by the _**api-release.yml**_ workflow.
    > **Note**
    > This will involve updating the `version` attribute of the component with the API version that gets sent to the workflow.
    > Example: `<TutorialLink projectName="RenderingTextures" version="v1.0.0-preview.30"/>`
8. Update the _**api-release.yml**_ workflow to use the deno script to update the `<TutorialLink/>` components

---

```[tasklist]
### Acceptance Criteria
- [x] Separate root folder created on the site that will hold the solution and projects
- [x] Build status check workflow for the tutorial projects created
- [x] Build step added to the _**prod-release.yml**_ workflow
- [x] Build step added to the _**api-release.yml**_ workflow
- [x] deno script created to update the Velaptor NuGet packages in the tutorial projects for the _**api-release.yml**_ workflow
- [x] Create VSCode task for update nuget package script
- [x] Create VSCode launch configfor update nuget package script
- [x] Update _**api-release.yml**_ workflow to update csharp project nuget packages
- [x] Deno script created to update `<TutorialLink/>` components
- [x] `<TutorialLink/>` component internal URL updated
- [x] _**api-release.yml**_ workflow updated to use update `<TutorialLink/>` component deno script
- [x] Setup VSCode to ignore csharp tutorial project root folder in workspace
- [x] Update all imports that reference services to use an import map
- [x] Add status check to branch rule set for tutorial projects solution build
- [x] set default branch back to main
- [x] Setup api release workflow to do dry-runs
- [x] Setup prod release workflow to do dry-runs
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
