### ISSUE TITLE
📋Add a bonus section to the audio guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#143]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Add a bonus section to the **Audio** guide.  This bonus guide will have the user move all of the audio info from the title bar to some text rendered in the window.

**Things To Do:**
1. Create the guide
2. The bonus section will have a screen-shot of the finished result
3. Add separate keyboard instructions as text
4. The audio info will not include the instructions. It will contain the play status, current time, if paused, etc.
5. Add an admonition at the beginning of the bonus section to refer to the rendering text guide for more info about rendering text.
6. The logo in the top left shows the docusaurus logo instead of the Velaptor logo
    - This is only a problem during dev.  The prod site does not have this issue

### Acceptance Criteria

```[tasklist]
- [ ] Create the guide
- [ ] The bonus section will have a screen-shot of the finished result
- [ ] Add separate keyboard instructions as text
- [ ] The audio info will not include the instructions like in the title bar, but as play status, current time, if paused, etc.
- [ ] Admonition added to the beginning of the bonus section
- [ ] New bonus section added to v1.0.0-preview.35
- [ ] New bonus section added to Next
- [ ] Audio guide csharp project updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
