### ISSUE TITLE
📜/🛡️Guide & API Doc Change - 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#149]
### Complete The Item Below

- [X] I have added the version to the very end of the issue title.
- [X] I have updated the title without removing the 🛡️ and 📜 emoji.

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [ ] Stuff
```

### ToDo Items

- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] If more than 5 versions exist after adding the new version, the oldest version is removed.

### Additional Information:

**Priority Type Labels**
| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |

> **Note**
> Removing a version of the API docs can be done by executing the _**Delete API Docs**_ VSCode task.
> Just follow the CLI instructions to remove the version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
