### ISSUE TITLE
📋Improve the CLI and Directory types

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#162]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Make improvements to the `CLI` class to better handle directory and file paths as well as make use of the `Deno.execPath()` API.

**CLI Class Code:**
```ts
/**
 * A simple CLI command wrapper.
 */
export class CLI {
	/**
	 * Runs the following CLI {@link command}.
	 * @param command The command to run.
	 * @returns The output of the command if successful, otherwise an error.
	 */
	public async runAsync(command: string): Promise<string | Error> {
		if (command === undefined || command === null || command === "") {
			const errorMsg = "The command parameter cannot be null or empty.";
			console.log(errorMsg);
			Deno.exit(1);
		}

		command = command.includes("'")
			? command.replace(/'/g, '"')
			: command;

		const sections: string[] = command.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g) ?? [];

		const app = sections[0] === "deno" ? Deno.execPath() : sections[0];
		const args = sections.slice(1).map(arg => arg.replace(/"/g, ''));

		const cmd = new Deno.Command(app, { args: args });

		const { code, stdout, stderr } = await cmd.output();

		if (code === 0) {
			return new TextDecoder().decode(stdout);
		} else {
			return new Error(new TextDecoder().decode(stderr));
		}
	}
}
```

**Directory.getFiles() Function**
```ts
/**
 * Gets a list of files in the given {@link dirPath}.  This will search recursively
 * if {@link recursive} is true.
 * @param dirPath The path of the directory start searching.
 * @param extension The file extension to search for.
 * @param recursive True to search recursively, otherwise false.
 * @returns {string[]} A list of files in the given {@link dirPath}.
 */
public static getFiles(dirPath: string, extension:string, recursive = false): string[] {
	let files: string[] = [];

	extension = extension.trim();

	const extensionRegex = /\.[a-zA-Z]/g;

	extension = Utils.isNothing(extension) ? "*.*" : extension;

	if (extension != "*.*") {
		extension = extension.startsWith("*.") ? extension.substring(1) : extension;

		if (!extension.startsWith(".") || extension.length === 1) {
			const errorMsg = `The extension '${extension}' is not supported.\n` +
								`Must be a value of '*.*' or '*.<extension>'.`;
			console.log(errorMsg);
			throw new Error(errorMsg);
		}
	}

	if (dirPath === undefined || dirPath === null || dirPath === "") {
		const errorMsg = "The dirPath parameter cannot be null or empty.";
		console.log(errorMsg);
		Deno.exit(1);
	}

	dirPath = dirPath === "." || dirPath === "./" ? Deno.cwd() : dirPath;

	for (const dirEntry of Deno.readDirSync(dirPath)) {
		const entry = dirPath + "/" + dirEntry.name;

		if (recursive && dirEntry.isDirectory) {
			files = [...files, ...(Directory.getFiles(entry, extension, recursive))];
		} else if (dirEntry.isFile) {
			if (extension === "*.*") {
				files.push(entry);
			} else {
				if (entry.endsWith(extension)) {
					files.push(entry);
				}
			}
		}
	}

	return files;
}
```

**Adjust deno-check.ts Script:**
```diff
const files: string[] = Directory
-	.getFiles("/", ".ts", true)
+	.getFiles("./", ".ts", true)
	.filter(f => ignoreDirectories.every(ignoreDir => !f.startsWith(ignoreDir)));
```

### Acceptance Criteria

```[tasklist]
- [ ] `CLI` class improved
- [ ] _**deno-check.ts**_ script adjusted
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
The `Directory.ts` file does not exist anymore and the work to update the `CLI` class is not worth the effort.
