### ISSUE TITLE
🛡️API Doc Change - v1.0.0-preview.19

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#17]
### Complete The Item Below

- [X] I have added the version to the very end of the issue title.
- [x] I have added the https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%9B%A1%EF%B8%8Fapi%20doc%20changes label to the issue.
- [x] I have added one of the priority labels from the priority table below.

### Acceptance Criteria

- [x] I have locally executed the documentation processing scripts to generate new API documentation.
- [x] I have used the correct [Velaptor version](https://github.com/KinsonDigital/Velaptor/tags).

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**Priority Type Labels**
| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority         |  https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority  |
| Medium Priority  | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority  |

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
