### ISSUE TITLE
📋Fix an issue with the project links

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#182]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Fix an issue with the project links.

1. Fix an issue where the project link points to a version that represents a Velaptor API version, but no tag has been created to reference the project
2. Fix an issue where the project URLs point to a project path that is not correct.
- The path is currently `/v1.0.0-preview.31/SampleProjects/RenderingText`
- The path should be `/v1.0.0-preview.31/SampleProjects/Guides/RenderingText`
3. Update the _**api-release.yml**_ workflow to create a tag that represents the Velaptor API version. This tag should be the API version prefixed with the text `api-`.  
> [!Note]
> Example: `api-v1.0.0-preview.31`
4. Make sure that all of the previous API versions of the docs point to either the old **_VelaptorTutorials_** project or the new sample projects in the docs website.

### Acceptance Criteria

```[tasklist]
- [x] Project URL links fixed
- [x] _**api-release.yml**_ workflow updated
- [x] all current version api tags created and updated for other guide versions
```

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
