### ISSUE TITLE
📜Change API doc release process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#19]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Change how API releases are performed.  Currently, the API release workflow creates ALL of the API documents and automates the version creation.  After this is done, it then tries to push those changes to master.  This does not work anymore because the master branch has protection rules on it so the workflow will never pass.

Move the document creation process to scripts that can be executed locally.  This will then create the changes that will become a pull request to the master branch.

The API release process will be refactored to only check everything and perform a release with tag from the master branch, but not create and process the documents.

### Acceptance Criteria

- [x] API release workflow changed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label           |
|--------------|-----------------|
| New Docs     | `✨new docs`    |
| CICD Changes | `cicd`          |
| Doc Changes  | `📝doc changes` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
