### ISSUE TITLE
fix(deps): update dependency prism-react-renderer to v2.4.1 - autoclosed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#2]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create various tutorials on how to get started and more.

### Acceptance Criteria

- [x] Tutorial docs added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label           |
|--------------|-----------------|
| New Docs     | `✨new docs`    |
| CICD Changes | `cicd`          |
| Doc Changes  | `📝doc changes` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
