### ISSUE TITLE
⚙️Fix broken API anchor links

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#209]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Fix all of the broken anchors that are being displayed as a warning during the build process.
After some light investigation, it seems that the issue is with the API doc generation process.

[docusaurus-warning.txt](https://github.com/KinsonDigital/VelaptorDocs/files/14978061/docusaurus-warning.txt)

### Acceptance Criteria

```[tasklist]
- [ ] Broken links fixed
```

### ToDo items

```[tasklist]
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update      |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
After doing some research and testing, we could not find out why it was doing this.  After some questions on the Docusaurus discord server, it was mentioned that they think this is a known issue with trailing slash URLs.

Issue will possibly be resolved in a future release.
