### ISSUE TITLE
⚙️Fix markdown processing bug and improve cicd system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#213]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Improve the CICD system by doing the following:

1. Replace the _**chalk**_ npm package with the deno module _**crayon**_
2. Update the cliffy package to the latest version
3. Update the _**generate-new-api-docs.ts**_ script to pull a list of Velaptor versions and have the user choose which one instead of typing it in manually.  This is only in interactive mode.
4. Remove the unused function `DocProcessor.findDirPaths()`
5. Fix issue with processing `{` and `}` characters in markdown docs.
These characters are causing build errors with Docusaurus.  The reason is that the characters exist in the markdown docs due to the characters existing in C# code docs.  Docusaurus does not convert these to the correct HTML equivalent so we have to do it manually. This means we have to use the HTML entities `&#123` for `{` and `&#125` for `}`.
Update the markdown processing system to replace this when they exist inside of markdown files.
6. Fix the _**Enable Next Version**_ and _**Disable Next Version**_ VSCode tasks
7. Fix the _**Toggle Testing Environment**_ task

> [!Note]
> Info about _**Next/Current Version**_ Fix
> The `includeCurrentVersion` bool setting in the _**docusaurus.config.js**_ file when commented out does not disable
> the feature. This is because when it is commented out, the default value is `true` which keeps it enabled.  The script needs 
> to be rewritten so that way it actually disables the bool value by changing it from `true` to `false`, not commenting out the line.
> Ways To Fix:
> 1. Only change the value of the bool prop and do not use commenting - PREFERRED
> 2. Set the default value to `false` and use commenting, but setting the flag to `true` would mean commented out and the flag as `false` would mean that it is not commented out.  

> [!Note]
> This is only an issue when the curly brace characters are outside of code blocks.  The processor is going to have to try and detect if the chars are inside or outside the code block before swapping them out with the equivalent HTML entities.
> The offending file that caused this issue is _**Velaptor.NativeInterop.ImGui.IImGuiInvoker.md**_

### Acceptance Criteria

```[tasklist]
- [x] Chalk package replaced
- [x] Cliffy deno module updated to the latest
- [x] _**generate-new-api-docs.ts**_ script updated to pull Velaptor versions
- [x] The function `DocProcessor.findDirPaths()` has been removed.
- [x] Curly brace HTML entity issue fixed
- [x] Update `next version` enabe/disable script
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update      |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
