### ISSUE TITLE
🚧Add twitter meta tags to home page

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#22]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Add Twitter meta tags to the homepage so the Twitter Cards will show appropriately.

References:
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

### Acceptance Criteria

- [x] Twitter meta tags added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                            |
|--------------|----------------------------------|
| New Docs             | https://github.com/KinsonDigital/VelaptorDocs/issues?q=is%3Aopen+label%3A%22%F0%9F%93%9Ctutorial+doc+changes%22 |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
