### ISSUE TITLE
📜Create scenes guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#226]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create a guide about creating and managing scenes.

**Subjects to cover:**
1. Creating a scene
2. Loading scene content
3. Updating scene content
4. Rendering scene content
5. Unloading scene content
6. Switching scenes
7. Difference between using the scene manager vs self-management

> [!Note]
> Look into possibly doing sub-pages doing managed vs unmanaged scenes

The overall application in the sample projects will have 2 scenes.  The first scene will have the KinsonDigital logo and the second scene will contain the Velaptor logo.  To keep things easy, both scenes will have the logo follow the mouse.

Pressing the right arrow key will move to the next scene while the left arrow key will move to the previous scene.  Scene switching will not wrap to the beginning or end.   Though this can be done, we want to force the user to move to the first and second scenes for the purposes of learning.

**Example:** If we are at the last scene, hitting the right arrow key will not navigate back to the first scene.

Also, add text to both scenes at the top center of the screen with instructions on how to move to the next and previous scenes. The text should include the scene's name.

### Acceptance Criteria

```[tasklist]
- [x] Section about creating a scene added
- [x] Section about loading a scene added
- [x] Section about updating a scene added
- [x] Section about rendering a scene added
- [x] Section about unloading a scene added
- [x] Section about switching scenes added
- [x] Discuss the advantages of adding scenes to the manager vs managing it by yourself
- [x] Discussion added about not requiring the use of a batcher in the scenes
- [x] Move the keyboard and mouse input into the same folder. The main folder should be named 'Input'
- [x] Check all GuideAudio components to make sure they are not in test mode
- [x] Highlighting added to code snippets
- [x] Add code line numbering for all code snippets
- [x] The word 'step' removed from all `sub-steps` and `sub-step-item`
- [x] Enable 'next' feature in production
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
