### ISSUE TITLE
📜Fix spelling and  grammar issues

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/VelaptorDocs#228]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Fix spelling and grammar issues and broken URL

### Acceptance Criteria

```[tasklist]
```

### ToDo Items

```[tasklist]
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
