### ISSUE TITLE
⚙️Fix broken anchor issue in api doc generation 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#230]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

The API docs generation process is producing broken anchors. 

These broken anchors are simply not the correct casing and name.

Real Example:
Take this markdown below.
`[Width](Velaptor.SizeU.md#Velaptor.SizeU.Width)`

Also, this is the actual anchor.
`### Width`

The anchor portion in the markdown linked is `Velaptor.SizeU.Width`.
This anchor is invalid because it links to an anchor at the bottom of the page, but it is not formatted correctly.

An anchor should be all lowercase, and spaces replaced with hyphens.

The correct formatting for this anchor should be as follows:
`[Width](Velaptor.SizeU.md#width)`

When it comes to anchors with multiple words:

The anchor `### My anchor Is cool`
It would become `my-anch-is-cool`

This is a list of all the broken anchors: 
[broken-anchors-list.txt](https://github.com/user-attachments/files/16579775/broken-anchors-list.txt)

> [!Note]
> This is generated as a list of warnings when running `pnpm build`

### Acceptance Criteria

```[tasklist]
- [x] API Doc generation process fixed to stop producing broken anchors
- [x] Fragments with type parameters processed
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency%20update      |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
