### ISSUE TITLE
📜Create guide for rendering rectangles

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#239]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create a guide about how to create rectangles.

### Acceptance Criteria

```[tasklist]
- [x] Guide sample project created
- [x] Guide covers solid vs not solid
- [x] Guide covers color
- [x] Guide covers border thickness
- [x] Guid covers width and height
- [x] Guide covers color gradients
- [x] Guide covers corner radius
- [x] Guide copied to other versions
- [x] All `class` attributes changed to `className` in `mdx` files
- [x] All docs for _**v1.0.0-preview.31**_ removed
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
