### ISSUE TITLE
📜Create new guide on rendering lines

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#244]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create a new guide on rendering lines. Follow the same overall pattern and layout of the rendering rectangles guide.

### Acceptance Criteria

```[tasklist]
- [x] Rendering lines guide created
- [x] All over versions updated with the same guide
- [x] Guide has content about `Render()` method
- [x] Guide has content about `RenderLine()` method overloads
- [x] Render lines coming soon page removed from all versions
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
