### ISSUE TITLE
📜Copy render rect guide to other versions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#246]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Currently, only the **_next_** version contains the guide for rendering rectangles.

The rest of the versions do not have the render rectangles guide. Copy the render rect guide from the _**next**_ version to the rest of the versions

### Acceptance Criteria

```[tasklist]
- [x] Render rectangle guide copied to the rest of the versions
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
