### ISSUE TITLE
📜Create a new rendering circles guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#252]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create a new guide about rendering circles.  This new guide will go under the rendering shapes category.

1. The _**Rendering Shapes**_ category should also be called **_Rendering Primitives_**. 
2. Make sure that the new guide is added to all of the other current versions
3. Guide project created

### Acceptance Criteria

```[tasklist]
- [x] The _**Rendering Shapes**_ category has been renamed to _**Rendering Primitives**_
- [x] Rendering circles guide created
- [x] Guide added to other versions
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
