### ISSUE TITLE
📜Add a simple guide on scenes and window size

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#253]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Add a small guide in the _**Scenes**_ category about how to get updates to the window size in your scenes.

1. The name of the guide should be _**Scenes & Window Size**_

> [!Warning]
> Only add this guide to the _**Next**_ version.  Not the other versions.  This is because the updated for this feature is what is coming up next.   It has not been released yet.

### Acceptance Criteria

```[tasklist]
- [x] New guide for scenes and window size created
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
