### ISSUE TITLE
📋Adjust meta data image size

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#26]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Adjust the size of the meta-data image that is visible when sending a tweet.
Below is an image of what it looks like on twitter.

Also, do some research to find out what the recommended size should be if there is a recommended size.

![image](https://user-images.githubusercontent.com/85414302/231434945-2bdb7b2d-cae2-4116-bf57-28af363191f8.png)

### Acceptance Criteria

- [x] Image shrunk to a more visible size
- [x] Remove the paragraphs of text for each section

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
