### ISSUE TITLE
📜/🛡️Guide & API Doc Change - Create updates for v1.0.0-preview.37

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#268]
### Complete The Item Below

- [X] I have added the version to the very end of the issue title.
- [X] I have updated the title without removing the 🛡️ and 📜 emoji.

Add and/or update docs related to content management explaining the following
- Fully qualified content paths
- Relative content paths
- Paths with and without extensions

### Spelling Error:
Fix a spelling error on [this page](http://localhost:3000/docs/guides/guides/adding-content).
<img width="411" alt="image" src="https://github.com/user-attachments/assets/e6a5e08d-0807-427c-98fc-81123a4a7e43">

### Broken Image:
There is a broken image on the [Rendering Textures](https://docs.velaptor.io/docs/guides/guides/rendering-textures/#step-3-load-and-unload-the-content) page.  This image is supposed to show the Velaptor mascot.

> [!Note]
> Verify that the image works on all versions.

### Acceptance Criteria

```[tasklist]
- [x] Add docs related to content management
- [x] Generate API docs
- [x] Oldest version of docs removed
- [x] Fix grammar for all issue templates
- [x] Fix label links in all issue templates
- [x] Fix all NOTE blocks in all issue templates
- [x] Spelling error fixed
- [x] Broken image link fixed
- [x] Fix all console errors in browser dev tools
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**Priority Type Labels**
| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |

> [!Note]
> Removing a version of the API docs can be done by executing the _**Delete API Docs**_ VSCode task.
> Just follow the CLI instructions to remove the version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
