### ISSUE TITLE
📜Add info about showing status window

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#279]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Add information in the docs about how to show the current stats in **_Velaptor_**.

Currently, to show the stats window which shows FPS, you use the key combination `Ctrl + Shift + Alt + S`.

Add the following information:
1. How to enable and disable the status window using a prop on the `Window` class
2. How to change the key combination using a prop on the `Window` class

### Acceptance Criteria

```[tasklist]
- [x] Information about showing the status window added to site
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LeaDevelop** [comment]
I volunteer to take care of the issue.
Only question I have is where do you expect this instructions and exactly of adjust keybinds to be be placed in the documentation?
I'll prepare first draft and regarding wording and all I imagine we go back and forth till your liking :)

**Comment by CalvinWilkinson** [comment]
> I volunteer to take care of the issue. Only question I have is where do you expect this instructions and exactly of adjust keybinds to be be placed in the documentation? I'll prepare first draft and regarding wording and all I imagine we go back and forth till your liking :)

Very good question.  I will take a quick look and see where to put it.

**Comment by CalvinWilkinson** [comment]
@LeaDevelop 

I was thinking of putting it in the [rendering textures](https://docs.velaptor.io/docs/next/guides/guides/rendering-textures#step-5-run-it) section at the very end.  Once somebody starts seeing something rendered to the screen, this would be a great time to see how it performs.  

Maybe a Tip admonition?

I am open to your thoughts as well!!

![Image](https://github.com/user-attachments/assets/3a699dac-e8c4-4ba1-8740-61aa6563c426)

**Comment by LeaDevelop** [comment]
My thoughts were alike was thinking bottom of this section as well and tip admonition too, we got this 💪🏻
I'll have first draft ready soon :)

**Comment by LeaDevelop** [comment]
@CalvinWilkinson would appreciate hint here, I had an attempt in Game.cs on EmptyProject sample to introduce customized key combination that does same as CTRL+SHIFT+ALT+S.

Q1. But I'd be getting cannot resolve symbol ShowStatsWindow, what approach are we expected to use here, or I'd have to touch engine source code to make it neat?

Q2. My approach on writing documentation is from point, if a game dev takes the project without engine source code, are they able to built the game, or is perhaps that's not the expectation?
```
    protected override void OnUpdate(FrameTime frameTime)
    {
        var currentKeyboardState = this.keyboard.GetState();

        // Toggle stats window with custom key combination (Ctrl + O)
        if (currentKeyboardState.IsKeyDown(KeyCode.LeftControl) &&
            currentKeyboardState.IsKeyDown(KeyCode.O) &&
            this.prevKeyboardState.IsKeyUp(KeyCode.O))
        {
            this.ShowStatsWindow = !this.ShowStatsWindow;   // <-------------------------- I am using wrong approach I guess. I also tried IsStatsWindowService but would then get protection level error. 0>Game.cs(29,22): Error CS0122 : 'IStatsWindowService' is inaccessible due to its protection level
        }

        this.prevKeyboardState = currentKeyboardState;

        // TODO: Update game state here
        base.OnUpdate(frameTime);
    }
```

Q3. For personal preference I introduced me FPS counter in the game title bar, let me know if you'd like that published somewhere in some sample or introduced to source.

![Image](https://github.com/user-attachments/assets/0092a9df-53e6-4987-9b9e-0ca2fdb418b5)
