### ISSUE TITLE
⚙️Update deno to latest

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#281]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Update to the latest version of deno and make various changes to take advantage of the new deno features.

1. Update deno to the latest version by updating the repository variable named `DENO_VERSION`.
2. Also, update the deno `build` task by using the new [globbing feature](https://deno.com/blog/v1.46#glob-support-for-deno-check-and-deno-cache-arg) with the release of deno.  This means that we no longer need to execute the _**deno-check.ts**_ file which means we can remove it entirely.
3. Update all workflows to use the new globbing feature instead of the _**deno-check.ts**_ script.
4. Remove the launch config in the _**launch.json**_ file for the _**deno-check.ts**_ script.
5. Remove the task config in the _**task.json**_ file for the _**deno-check.ts**_ script.

> [!Note]
> The version of deno as of the creation of this issue was _**v1.4.6**_.  If the version is greater than that, update to the latest.

### Acceptance Criteria

```[tasklist]
- [x] Deno version repo variable updated to the latest version
- [x] Deno `build` task updated to use the new globbing pattern feature
- [x] The `deno-check.ts` file has been deleted
- [x] All workflows updated
- [x] The _**launch.json**_ file has been updated
- [x] The _**tasks.json**_ file has been updated
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
