### ISSUE TITLE
📜/🛡️Guide & API Doc Change - v1.0.0-preview.38

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#285]
### Complete The Item Below

- [X] I have added the version to the very end of the issue title.
- [X] I have updated the title without removing the 🛡️ and 📜 emoji.

1. Update the API docs for the upcoming release.
2. Update the _**Render With An Atlas Texture**_ guide to use the new render atlas texture overloads.

### Acceptance Criteria

```[tasklist]
- [x] Changes to the _**Render With An Atlas Texture**_ guide has been performed
- [x] Oldest api docs removed
- [x] API Changes have been performed
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**Priority Type Labels**
| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |

> [!Note]
> Removing a version of the API docs can be done by executing the _**Delete API Docs**_ VSCode task.
> Just follow the CLI instructions to remove the version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
