### ISSUE TITLE
⚙️Misc cleanup

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#295]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Remove the `manual-testing` directory and all of its contents from the repository.

This will also require updating various configuration files.

1. Update the `reload-cache` deno task like the following below:
    ```diff
    - "reload-cache": "deno cache -r './.github/cicd/core/**/*.ts' './.github/cicd/manual-testing/**/*.ts' './.github/cicd/scripts/**/*.ts'"
    + "reload-cache": "deno cache -r './.github/cicd/core/**/*.ts' './.github/cicd/scripts/**/*.ts'"
    ```
2. In the _**launch.json**_ config file, remove the launch config object below:
    ```json
    { // RESET DOCS
        "request": "launch",
        "name": "Reset Docs",
        "type": "node",
        "program": "${workspaceFolder}/.github/cicd/manual-testing/reset-docs.ts",
        "cwd": "${workspaceFolder}/.github/cicd",
        "runtimeExecutable": "${userHome}/.deno/bin/deno.EXE",
        "runtimeArgs": [
            "run",
            "--inspect-wait",
            "--allow-all",
        ],
        "attachSimplePort": 9229
    },
    ```
3. In the _**tasks.json**_ config file, remove the config object below:
    ```json
    { // RESET DOCS
	    "label": "Reset Docs",
	    "detail": "Resets the docs to the default state.",
	    "type": "shell",
	    "options": {
		    "cwd": "${workspaceFolder}/.github/cicd"
	    },
	    "command": "deno",
	    "args": [
		    "run",
		    "--allow-read",
		    "--allow-write",
		    "'${workspaceFolder}/.github/cicd/manual-testing/reset-docs.ts'"
	    ]
    },
    ```
5. Remove the _**reset-docs.ts**_ file.

### Acceptance Criteria

```[tasklist]
- [x] The `reload-cache` deno task has been updated
- [x] Launch config has been removed
- [x] Task config has been removed
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LeaDevelop** [comment]
Hello, I'm currently on-boarding of the repository and reading through guidelines. I'd like to volunteer to take care of the issue (am open to pair up - if somebody else wants to give it a try as well, don't make my attempt block you 😉).

**Comment by LeaDevelop** [comment]
Acceptance criteria progress can be checked in #302. 
Should any of following files also be looked into by any chance, or is reference to manual testing not related to manual-testing directory?

- `docasaurus.config.ts`
- `intro.mdx`
- `*-preview*\...\intro.mdx`
- `.gitignore`
- `sidebars.ts`

**Comment by CalvinWilkinson** [comment]
> Acceptance criteria progress can be checked in [#302](https://github.com/KinsonDigital/VelaptorDocs/pull/302). Should any of following files also be looked into by any chance, or is reference to manual testing not related to manual-testing directory?
> 
> * `docasaurus.config.ts`
> * `intro.mdx`
> * `*-preview*\...\intro.mdx`
> * `.gitignore`
> * `sidebars.ts`

This is a very good point.  I had some scripts and configs set up in the past that used that directory when the website was first being developed.  Since things have changed so much, the config and scripts are not needed anymore, so they are being cleaned up. 

When I review your PR, I will look into this further, and if I find anything else, I will let you know. 

Good thinking!!

**Comment by CalvinWilkinson** [comment]
@LeaDevelop 

After looking at the files, I did not find anything related to manual testing.

But I did find some other things that could be cleaned up.  Instead of doing it in this issue, I will create more hacktoberfest issues.  I have had more people join the Discord server today, so I had better create more.  😉

Good eye!!
