### ISSUE TITLE
📜Fix grammar issues with audio guides

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#296]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Fix the grammar issue in the audio guides. The mistake is shown below.
The mistake is in the `Step 3: Setup window` section of the page.

> [!Note]
> The word `create` is used 2 times in a row.

```txt
Let's set up our window to not be so large, create an object to detect keyboard input, and create
create the audio loader to load audio content.
```

The grammar issue is in the following versions of the docs:
- `v1.0.0-preview.35`
- `v1.0.0-preview.36`
- `v1.0.0-preview.37`
- `v1.0.0-preview.38`

This means the following files need to be updated:
- `docs/guides/guides/audio.mdx`
- `versioned_docs/version-1.0.0-preview.35/guides/guides/audio.mdx`
- `versioned_docs/version-1.0.0-preview.36/guides/guides/audio.mdx`
- `versioned_docs/version-1.0.0-preview.37/guides/guides/audio.mdx`
- `versioned_docs/version-1.0.0-preview.38/guides/guides/audio.mdx`

### Acceptance Criteria

```[tasklist]
- [x] The grammar issue ahs been fixed in the audio docs page for version `v1.0.0-preview.35`
- [x] The grammar issue ahs been fixed in the audio docs page for version `v1.0.0-preview.36`
- [x] The grammar issue ahs been fixed in the audio docs page for version `v1.0.0-preview.37`
- [x] The grammar issue ahs been fixed in the audio docs page for version `v1.0.0-preview.38`
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by madhummitha** [comment]
Hi @CalvinWilkinson 
Can I pick this up?

**Comment by CalvinWilkinson** [comment]
> Hi @CalvinWilkinson Can I pick this up?

Absolutely!!  Just as a quick reminder, make sure to ask questions and review the [contribution guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md).  

I am here if you need me.  You can also join the [discord server](https://discord.gg/qewu6fNgv7) if you wish.
