### ISSUE TITLE
⚙️Update vscode config file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#297]
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Update the _**extensions.json**_ config file to ignore the **C# Dev Kit** vscode extension recommendation.

This can be done by updating the file as shown below:
```diff
{
	"recommendations": [
		"simonsiefke.svg-preview",
		"yzhang.markdown-all-in-one",
		"unifiedjs.vscode-mdx",
		"mistermunchkin.simple-markdown-snippets"
-	]
+	],
+	"unwantedRecommendations": [
+		"ms-dotnettools.csdevkit"		
+	]
}
```

### Acceptance Criteria

```[tasklist]
- [x] The C# DevKit vscode extension has been set to ignore recommandations
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by bmonish** [comment]
Hi @CalvinWilkinson Can I work on this?
