### ISSUE TITLE
📜Update paragraph in project setup guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#298]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update the paragraph in the **Project Setup** guides to improve clarity and readablity.

**This is the current paragraph:**
```txt
If you want to have your game react when the window size changes, you can create a method override of the `Window.OnResize()` method.
The `OnResize()` method is invoked anytime the window's size is changed. This includes minimizing, maximizing, and restoring the window.
This is a great location to run game logic that can do anything you need. One good example is to pause your game automatically
when minimized and to unpause when the window is maximized or restored.
```

**Update the paragraph to:**
```txt
If you want your game to react when the window size changes, you can create an override method using the `Window.OnResize()` method.
The `OnResize()` method is invoked anytime the window's size is changed, including minimizing, maximizing, and restoring it.
This is a great location to run game logic that can do anything your game needs. One good example is to pause your game automatically
when minimized and to unpause when the window is maximized or restored.
```

> [!Note]
> Update the other following versions of the guide to the same text:
> - Next
> - v1.0.0-preview.34
> - v1.0.0-preview.35
> - v1.0.0-preview.36
> - v1.0.0-preview.37
> - v1.0.0-preview.38

These are the file paths to the project setup guides relative to the root of the repository that need to be updated:
- docs/guides/guides/project-setup.mdx
- versioned_docs/version-1.0.0-preview.34/guides/guides/project-setup.mdx
- versioned_docs/version-1.0.0-preview.35/guides/guides/project-setup.mdx
- versioned_docs/version-1.0.0-preview.36/guides/guides/project-setup.mdx
- versioned_docs/version-1.0.0-preview.37/guides/guides/project-setup.mdx
- versioned_docs/version-1.0.0-preview.38/guides/guides/project-setup.mdx

### Acceptance Criteria

```[tasklist]
- [x] The _**project-setup.mdx**_ guide for the version `Next` has been updated
- [x] The _**project-setup.mdx**_ guide for the version `v1.0.0-preview.34` has been updated
- [x] The _**project-setup.mdx**_ guide for the version `v1.0.0-preview.35` has been updated
- [x] The _**project-setup.mdx**_ guide for the version `v1.0.0-preview.36` has been updated
- [x] The _**project-setup.mdx**_ guide for the version `v1.0.0-preview.37` has been updated
- [x] The _**project-setup.mdx**_ guide for the version `v1.0.0-preview.38` has been updated
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by bmonish** [comment]
Hi @CalvinWilkinson Can I work on this?
