### ISSUE TITLE
📋Add processing to API docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#30]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Add additional processing to the API docs to adjust the headers in each file based on if the header is a _**Method**_ or _**Property**_ category.

**The header and line criteria are below:**
1. Method Group line increase by 1
2. Method lines decrease by 1
3. Property Group line increase by 1
4. Property lines decrease by 1
5. Constructor Group line increase by 1
6. Constructor lines decrease by 1
7. Remarks lines decrease by 1
8. Fields Group line decrease by 1

**Other processing:**
1. Find all method signature lines and remove the namespace/class name from the beginning of the method name
    > **Note** Removing class names with generics might prove to be a challenge

**Before Processing:**
![image](https://user-images.githubusercontent.com/85414302/232517760-29532b1d-a39a-4f1e-bc8a-be5f9cb97d25.png)

**After Processing:**
![image](https://user-images.githubusercontent.com/85414302/232518068-0e6dc07f-162d-4d4f-b288-3bc926c323d9.png)

### Acceptance Criteria

- [x] Method Group line increased by 1
- [x] Method lines decreased by 1
- [x] Property Group line increased by 1
- [x] Property lines decrease by 1
- [x] Constructor Group line increased by 1
- [x] Constructor lines decreased by 1
- [x] Remarks lines decreased by 1
- [x] Fields Group line decreased by 1
- [x] All method signature lines and remove the namespace/class name from the beginning of the method name

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
