### ISSUE TITLE
🏗️Update status checks to be executed by forks

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#303]
### Complete The Item Below

- [x] I have updated the title without removing the 🏗️ emoji.

### Description

Go through each status check and update it to be able to be executed by workflows.

This requires that the `pull_request_target` trigger be used so the workflow has access to repository variables.  This means we need to be explicit with the repository checkout action so it checks out the code from the fork and the source and mixes the code to the code for both has been merged.

### Acceptance Criteria

```[tasklist]
- [x] All status checks updated appropriately
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
