### ISSUE TITLE
⚙️Remove config comments from config files

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#309]
### Complete The Item Below

- [x] I have updated the title without removing the ⚙️ emoji.

### Description

Remove various config comments from the following files:
- _**docusaurus.config.ts**_
- _**sidebars.ts**_

**Reason:**
This is because these comments were special comments used by custom scripting to enable and disable these config values.  These were used in the site's early days, but the scripts and their use have been removed.  They are not required anymore.

_**docusaurus.config.ts**_ comment removal (1):
```diff
- // ⚠️DO NOT CHANGE THIS⚠️
- // This is used as part of the manual testing process for the CICD side of the project.
- // <flag id=api enabled=true>
{
    type: 'doc',
    docId: 'api/Namespaces',
    position: 'left',
    label: 'API',
},
```

_**docusaurus.config.ts**_ comment removal (2):
```diff
{
    href: 'https://discord.gg/qewu6fNgv7',
    position: 'right',
    className: "header-discord-link"
},
- // ⚠️DO NOT CHANGE THIS⚠️
- // This is used as part of the manual testing process for the CICD side of the project.
- // <flag id=testing enabled=false>
- // {
- // type: 'doc',
- // label: 'API Testing',
- // position: 'left',
- // docId: 'api/Namespaces',
- // },
- // </flag>
```

_**sidebars.ts**_ comment removal (2):
```diff
- // ⚠️DO NOT CHANGE THIS⚠️
- // This is used as part of the manual testing process for the CICD side of the project.
- // <flag id=api enabled=true>
api: [{type: 'autogenerated', dirName: 'api'}],
- // </flag>
```

### Acceptance Criteria

```[tasklist]
- [x] The comments in the _**docusaurus.config.ts**_ have been removed
- [x] The comments in the _**sidebars.ts**_ have been removed
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by LeaDevelop** [comment]
I can take this one, if no one is on it :)
