### ISSUE TITLE
📜Remove and fix links in intro

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#310]
### Complete The Item Below

- [x] I have updated the title without removing the 📜 emoji.

### Description

In the intro page for all of the versions of the website, do the following:
1. Remove the link with the name _**Kristen Wilkinson**_
```diff
- by [Calvin Wilkinson](https://x.com/KDCoder) and [Kristen Wilkinson](https://x.com/kswilky)
+ by [Calvin Wilkinson](https://x.com/KDCoder)
```
2. Fix the broken link to the license file
```diff
- Velaptor is a free and open-source project, released under the permissible [MIT license](https://github.com/KinsonDigital/Velaptor/blob/preview/v1.0.0/LICENSE.md)
+ Velaptor is a free and open-source project, released under the permissible [MIT license](https://github.com/KinsonDigital/Velaptor/blob/preview/LICENSE.md)
```

Various versions of the site contain the changes that need to be made.  The files for each of the versions are below:
1. docs/guides/intro.mdx
2. versioned_docs/version-1.0.0-preview.35/guides/intro.mdx
3. versioned_docs/version-1.0.0-preview.36/guides/intro.mdx
4. versioned_docs/version-1.0.0-preview.37/guides/intro.mdx
5. versioned_docs/version-1.0.0-preview.38/guides/intro.mdx

### Acceptance Criteria

```[tasklist]
- [x] The link updates in the file _**docs/guides/intro.mdx**_ have been performed
- [x] The link updates in the file _**versioned_docs/version-1.0.0-preview.35/guides/intro.mdx**_ have been performed
- [x] The link updates in the file _**versioned_docs/version-1.0.0-preview.36/guides/intro.mdx**_ have been performed
- [x] The link updates in the file _**versioned_docs/version-1.0.0-preview.37/guides/intro.mdx**_ have been performed
- [x] The link updates in the file _**versioned_docs/version-1.0.0-preview.38/guides/intro.mdx**_ have been performed
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by Bashamega** [comment]
Hello:)
I would like to work on this issue

**Comment by CalvinWilkinson** [comment]
> Hello:) I would like to work on this issue

I have assigned the issue to you.  If you have any questions, please don't hesitate to ask!

If you are interested, you can join the [discord channel](https://discord.gg/qewu6fNgv7) to ask for help and also ask questions.
