### ISSUE TITLE
📜Remove hardcoded dotnet version reference

### ISSUE THREAD

**Issue by LeaDevelop** [KinsonDigital/VelaptorDocs#320]
### Complete The Item Below

- [x] I have updated the title without removing the 📜 emoji.

### Description

Following line is currently out of date based on the change in https://github.com/KinsonDigital/Velaptor/commit/1ce17e9dd55a900a1c263eaba11d627d90853f28

```suggestion
- Create a new C# console application using dotnet _**v7.0**`
+ Create a new C# console application using dotnet version specified in the EmptyProject.csproj
```

### Acceptance Criteria

```[tasklist]
- [x] Documentation updated to: Create a new C# console application using dotnet version specified in the `EmptyProject.csproj`
```

### ToDo Items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by LeaDevelop** [comment]
Based on testing expanded original suggestion in the issue, felt like it would be neat to point out what exactly reader is expected to follow. Let me know what you think.

**Comment by CalvinWilkinson** [comment]
> Based on testing expanded original suggestion in the issue, felt like it would be neat to point out what exactly reader is expected to follow. Let me know what you think.

I think it is a great idea.  I made a little change to the text but I like the idea!

Check out the comment in the review for more info.
