### ISSUE TITLE
🏗️Fix issues with api release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#337]
### Complete The Item Below

- [x] I have updated the title without removing the 🏗️ emoji.

### Description

Fix an issue with the `update_csharp_project_files` job in the _**api-release.yml**_ workflow where the _**update-velaptor-nugets.ts**_ script is not being executed with environment variables.

Also, fix any other issues that might arise by testing out the api release workflow.

### Acceptance Criteria

```[tasklist]
- [x] The `update_csharp_project_files` job has been fixed.
- [x] Workflow testing and other discovered issues if any have been fixed
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
