### ISSUE TITLE
⚙️Update deno to the latest version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#339]
### Complete The Item Below

- [x] I have updated the title without removing the ⚙️ emoji.

### Description

Update deno to the latest version, which, as of the creation of this issue, is version _**v2.1.4**_.

Do the following:
1. Update the **DENO_VERSION** repo variable
2. Update all deno permissions to shorthand through the project

### Acceptance Criteria

```[tasklist]
- [x] The **DENO_VERSION** repo variable has been updated
- [x] All deno permissions in the code base have been converted to short hand
- [x] The `UpdateWebsiteVersionService` class code moved into the _**update-website-version.ts**_ file
- [x] All setup deno github actions updated to v2
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
