### ISSUE TITLE
📜Update headers for all tutorials

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#43]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update all of the headers for all of the tutorials to improve how the sections are displayed in the navigation section on the right of the webpage.

Currently, the sub-steps are not showing up in the navigation section due to Docusaurus hiding the header when the header uses 4 or more `#` hashtags.

All major steps with a whole number should be changed from 3 x `#` symbols to 2 x `#` symbols.
All sub-steps with a fractional number should be changed from 4 x `#` symbols to 3 x `#` symbols.

### Acceptance Criteria

- [ ] All tutorials are updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
