### ISSUE TITLE
chore(deps): update dependency typescript to ~5.7.0 - autoclosed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#5]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

This readme should have a simple setup and description.

This should also show some simple instructions on how to contribute with branching as well as with GIT and docusaurus commands.

### Acceptance Criteria

- [x] Project readme updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label           |
|--------------|-----------------|
| New Docs     | `✨new docs`    |
| CICD Changes | `cicd`          |
| Doc Changes  | `📝doc changes` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
