### ISSUE TITLE
📜 Add missing info to HelloVelaptor tutorial

### ISSUE THREAD

**Issue by sbundaz** [KinsonDigital/VelaptorDocs#54]
### Complete The Item Below

- [x] I have updated the title without removing the 📜 emoji.

### Description

I have followed the "Hello Velaptor" tutorial and there are some missing information about text color.

Here there is a missing variable "textColor":
<img width="909" alt="image" src="https://github.com/KinsonDigital/VelaptorDocs/assets/22452529/050df4f4-42fb-412e-b312-8509bba03b00">

At the end of part 4 I'd add another step 4.4 that suggests replacing this line of code:
<img width="896" alt="image" src="https://github.com/KinsonDigital/VelaptorDocs/assets/22452529/a62f3cf8-55fa-40aa-a35e-3e113ae5d96f">

I think the tutorial would be more easy to follow.

I would like to work on the issue.

### Acceptance Criteria

Acceptance Criteria:
 - [x] Add the missing variable
 - [x] Replace 'Color.Orange' with textColor variable inside OnDraw method.
 - [x] Update the guide for the following versions
 - [x] Current version.
     > **Note** Located in the _**/docs**_ folder
- [x] Update the guide for version _**v1.0.0-preview.18**_
    > **Note** Located in _**versioned_docs/version-1.0.0-preview.18**_
- [x] Update the guide for version _**v1.0.0-preview.19**_
    > **Note** Located in _**versioned_docs/version-1.0.0-preview.19**_
- [x] Update the guide for version _**v1.0.0-preview.20**_
    > **Note** Located in _**versioned_docs/version-1.0.0-preview.20**_
- [x] Update the guide for version _**v1.0.0-preview.21**_
    > **Note** Located in _**versioned_docs/version-1.0.0-preview.21**_

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
