### ISSUE TITLE
📜Fix code block issues

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#56]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Fix a spelling error in the code block in the _**Rendering Textures**_ guide, in **_Step 2.1_**.

**Update the code block to what is shown below:**
```diff
public class Game : Window
{
-    private ITextRenderer textureRenderer; // Renders textures
+    private ITextureRenderer textureRenderer; // Renders textures
}
```

**Update the code block with this simple code fix:**
```diff
public class Game : Window
{
-    private ITexture mascotTexture; // The texture to render
+    private ITexture? mascotTexture; // The texture to render
}
```

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Code block updated in guide _**Rendering Textures > Step 2.1**_
- [x] Change applied to guide version 1.0.0-preview.21
- [x] Change applied to guide version 1.0.0-preview.20
- [x] Change applied to guide version 1.0.0-preview.19
- [x] Change applied to guide version 1.0.0-preview.18
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
I want to fix it.

**Comment by CalvinWilkinson** [comment]
You are good to go @AndreBonda!!
