### ISSUE TITLE
📜Create sound tutorial guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#61]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Create a guide for how to play sounds.

### **Extra:**
Remove the **Mouse Input** guide from the coming soon section.
> **Note** The removal was forgotten when creating the guide.

Fix the name of the admonition for the guide source code in the **Mouse Input** tutorial.
![image](https://github.com/KinsonDigital/VelaptorDocs/assets/85414302/13e8a117-64ab-494b-9e84-fa3ea6aeb354)

### Acceptance Criteria

- [x] Sounds guide created
    - [x] Sounds guide added to each version of the docs
- [x] The **MouseInput** guide menu item was removed from the coming soon section
- [x] The **Sounds** guide item was removed from the coming soon section
- [x] Mouse input guide project template admonition
    - [x] Other versions of this guide updated as well

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
