### ISSUE TITLE
📜Add sounds guide to other versions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#64]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

In the previous release, the sounds guide was added to the NEXT version which is not usable in production and is only used for development.  The guide was created successfully but we forgot to add the guide to the rest of the doc versions.

Add the guide to the rest of the versions of the docs so it is available in production.

### Acceptance Criteria

- [x] Sound guide added to all of the doc versions

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
