### ISSUE TITLE
📋Update all deno scripts to latest version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#66]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Go through all of the deno script files and update them to the latest deno version.
This will involve changing the imports which are all pointing to a specific version.

But before we do this, let's investigate import maps to see if this is something we can make easier.

Go [here](https://deno.com/manual@v1.15.2/linking_to_external_code/import_maps) for deno docs on the subject.

The idea here is that we can possibly create a map called **deno-latest** or something similar and then update all of our imports to use that instead of the specific versions. This would make updating to a later version of deno much simpler.  This would allow us to only update the version in the map instead of having to go to every single file and update the imports invidibually.

Test this out by creating a sample project to see if this can work.  If it does not work, update all of the imports individually, it if does work, add the import map.

### Acceptance Criteria

- [ ] deno imports updated to latest

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
