### ISSUE TITLE
📜Update docusaurus to v2.4

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#7]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update Docusaurus to v2.4!!

> **Warning**
There was an announcement on the discord server and a note about issues with translations. This will probably not apply here but be wary of it.

[Here](https://github.com/facebook/docusaurus/discussions/8821) is the discussion on it.

### Acceptance Criteria

- [x] Update docusaurus to v2.4
- [x] Site heavily tested

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label           |
|--------------|-----------------|
| New Docs     | `✨new docs`    |
| CICD Changes | `cicd`          |
| Doc Changes  | `📝doc changes` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
