### ISSUE TITLE
📋Set up vscode settings for file tabbing

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#70]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Set up the vscode settings to set the tab settings for various files for the workspace.

This will involve adding the settings to the _**.vscode/settings.json**_ file. Add the settings as shown below.

```diff
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true,
        "build/": true
    }
+    "[typescript]": {
+		"editor.insertSpaces": false,
+		"editor.tabSize": 4,
+    },
+	"[yaml]": {
+		"editor.insertSpaces": true,
+		"editor.tabSize": 2,
+	},
+	"[jsonc]": {
+		"editor.insertSpaces": false,
+		"editor.tabSize": 4,
+	},
+	"editor.detectIndentation": false,
+	"[github-actions-workflow]": {
+		"editor.tabSize": 2,
+		"editor.insertSpaces": true
+	}
```

### Acceptance Criteria

- [x] Tab settings added for typescript files
- [x] Tab settings added for yaml files
- [x] Tab settings added for jsonc files
- [x] Indentation detection turned off for the editor
- [x] Tab settings added for the **GitHub Actions** VSCode extension

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
