### ISSUE TITLE
📋Improve generate api docs process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#80]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Improve the process of generating the API docs by improving the deno scripts.

The _**main.ts**_ script that is executed by the **VSCode** task named **Generate API Docs**, executes the `DocProcessor` class.  This class runs various dotnet and git commands to pull down a tag of the Velaptor repository and builds the project so the library can be used to generate the API doc markdown files.

Currently, this process just asks for and expects a tag to be used when cloning.  This technically can be used with a branch name due to the git command used.  Refactor the `DocProcessor` class to ask for a tag OR branch name.  If a tag name is chosen, validate with regex that the tag is a valid preview or production version. If a branch name is chosen, just run the process with the branch name.  

## **Purpose:**

Doing this will make things clearer and also add the capability to clone the docs and prepare the website without actually releasing **Velaptor** first.  This means that we can prepare a release in **Velaptor**, then create an issue and prepare all of the docs related to the upcoming **Velaptor** release.   Once everything is good to go, we can then release **Velaptor** and then this doc site with minimal time between them.

### Acceptance Criteria

- [x] `DocProcessor` class refactored to ask for a tag or branch name
- [x] If a tag name is chosen, version validation using regex is performed.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
