### ISSUE TITLE
📜Update all guides related to v1.0.0-preview.24 changes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#93]
### Complete The Item Below

- [X] I have updated the title without removing the 📜 emoji.

### Description

Update all of the guides related to the new changes from _**v1.0.0-preview.24**_

In this version of _**Velaptor**_, 4 new `bool` properties were added to the `IWindow` and `Window` types.  The behavior of these types, when set to a value of `true`, will automatically update, render, load, and unload the scenes that are in the scene manager.

> **Note**
> This description and code samples about the `IRenderer.Begin()` and `End()` need to be removed.  These don't need to be talked 

**This change will affect the following guides:**
about at this point in the guide due to the auto updates being set to `true`
1. Hello Velaptor: Step 3.4
2. Rendering Textures: Step 2.6
3. Rendering With An Atlas Texture: Step 7

> **Warning**
> ONLY UPDATE THE GUIDE FOR **v1.0.0-preview.24**
> These changes do not apply to older versions.

---

**Additional Changes:**
Auto-add issues created by all of the issue templates by adding a `projects: ["KinsonDigital/11"]` setting.
Also remove the _**Issue linked**_ and _**Draft pull request**_ checkboxes from the _**ToDo Items**_ section.

### Acceptance Criteria

- [x] All guides updated
    - [x] **_Hello Velaptor: Step 3.4_**
    - [x] Rendering Textures: Step 2.6
    - [x] Rendering With An Atlas Texture: Step 7

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
