### ISSUE TITLE
📋Create API only release system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VelaptorDocs#94]
### Complete The Item Below

- [X] I have updated the title without removing the 📋 emoji.

### Description

Create a workflow where we can perform an API release only.  This workflow will ONLY be used to release the website when there is a new API release of Velaptor.

To do this, we need to not only perform a normal release which is provided by the _**prod-release.yml**_ workflow, but we also need automatically check if there are at least 5 versions of the API that exist, then automatically delete the oldest API docs, create the new API docs, and then perform the release.

**Order of the process is as follows:**
1. Check how many API docs exist
2. If there are 5 or more API docs, find the API doc that is the oldest
3. Delete the oldest API docs
4. Generate a new API doc
5. Run the standard production workflow to perform a release.

**Things to do to make this a reality:**
1. The API release workflow needs to be capable of being run manually by using the `workflow_dispatch`
    > **Note**
    > This is important because the workflow will be executed from the Velaptor CICD system after a release is performed.
2. The current _**prod-release.yml**_ workflow needs to be converted to execute a docusaurus reusable workflow in _**Infrastructure**_.
3. The new _**api-release.yml**_ workflow will not only run the API deletion and creation process but then also execute the reusable docusaurus reusable workflow in _**Infrastructure**_.

**Other things to do:**
1. Replace all GitHub API-related requests to use the clients in _**Infrastructure**_.
    > **Note**
    > I think there is only 1 and it is in the `ValidateReleaseService` class.
2. Replace any usages of the `ChalkColor` class with the actual _**chalk**_ npm package.
    > **Note**
    > npm specifiers are not supported in deno.
3. Remove the `ChalkColor` class and all of its references
4. Fix the reference of the VSCode tasks to other tasks.
    > **Note**
    > In the _**tasks.json**_, there are 2 tasks that use the `dependsOn` JSON key to reference the `Disable Testing Environment` task but are not using the correct label.  The label being used is `disable-testing-env` but should be `Disable Testing Environment`.
5. Remove the following checkboxes from all of the issue templates
    - **_Priority label added to this issue. Refer to the Priority Type Labels section below._**
    - **_Draft pull request created and linked to this issue (only required with code changes)._**

### Acceptance Criteria

- [x] All GitHub API requests replaced with clients from ***Infrastructure***
- [x] Chalk code updates
    - [x] `ChalkColor` code replaced with npm package
    - [x] `ChalkColor` class and related code removed
- [x] VSCode tasks fixed
- [x] Issue templates updated
- [x] _**api-release.yml**_ workflow created
    - [x] `workflow_dispatch` added to the workflow
    - [x] Comment added to this trigger noting not to delete it due to it being used in Velaptor
    - [x] Validate branch job created
    - [x] API Doc Version Job
        - [x] Deletes oldest API doc step added
        - [x] Generate a new (latest) API doc step added
    - [x] Dependencies of other jobs on the validate branch job setup
- [x] Set the default branch back to main
- [x] Remove the feature branch from the `github-pages` environment deployment branch list

### Issue Dependencies

- KinsonDigital/Infrastructure#154

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type  | Label                                                                                             |
|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/%E2%99%BB%EF%B8%8Fcicd               |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/dependency%20update                  |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Tutorial Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Ctutorial%20doc%20changes |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
